version: '3.5'

volumes:
  mongodb_volume:

  vault_volume:

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
#    hostname: www.ourgit.io
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "8000:80"
      - "8822:22"
      - "8001:443"
    volumes:
      - ./config/gitlab:/etc/gitlab
      - ./data/gitlab:/var/opt/gitlab
      - ./logs:/var/log/gitlab
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab
    environment:
      GIT_SSL_NO_VERIFY: "true"
    expose:
      - "443"
    volumes:
      - ./config/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - gitlab
    networks:
      - gitlab

  terraform:
    image: hashicorp/terraform:1.1.5
    volumes:
      - .:/tf_vol
      - logvolume01:/var/log
    working_dir: /tf_vol
#    environment:
#      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
#      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
  ports:
    -

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
      image: mongo-express
      ports:
        - "8080:8081"
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_SERVER=mongodb
    volumes:
      - mongodb_volume:/data/db
    restart: always

networks:
  gitlab: